apiVersion: v2
name: sedaro-demo
version: 0.1.0
description: DaveOps implementation of Sedaro-Nano
dependencies:
  - name: prometheus
    version: 25.21.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: grafana
    version: 7.3.9
    repository: https://grafana.github.io/helm-charts